export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const AUTH_ERR = 'AUTH_ERR';
export const AUTH_START = 'AUTH_START';
export const AUTH_RESET = 'AUTH_RESET';
export const TOGGLE_STATUS = 'TOGGLE_STATUS';
export const FACTOR_SCREENER = 'FACTOR_SCREENER';
export const FACTOR_SCREENER_ERROR = 'FACTOR_SCREENER_ERROR';
// Strategy Builder Queries
export const COUNTRY_UPDATE = 'COUNTRY_UPDATE';
export const SECTOR_UPDATE= 'SECTOR_UPDATE';
export const FACTORS_UPDATE= 'FACTORS_UPDATE';
export const STOCK_UPDATE= 'STOCK_UPDATE';
export const FIRM_UPDATE='FIRM_UPDATE';
export const RESET_QUERY='RESET_QUERY';
export const FACTOR_SCREENER_RESET='FACTOR_SCREENER_RESET';
export const FACTOR_SCREENER_SAVE = 'FACTOR_SCREENER_SAVE';
export const FACTOR_SCREENER_SAVE_ERROR = 'FACTOR_SCREENER_SAVE_ERROR';
