export const SIGN_IN_A = 'SIGN_IN_A';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_OUT = 'SIGN_OUT';
export const AUTH_ERR = 'AUTH_ERR';
export const AUTH_RESET = 'AUTH_RESET';
export const TOGGLE_STATUS = 'TOGGLE_STATUS';
export const LOCATION_PATH = 'LOCATION_PATH';
// Strategy Builder Queries
export const COUNTRY_UPDATE = 'COUNTRY_UPDATE';
export const SECTOR_UPDATE= 'SECTOR_UPDATE';
export const FACTORS_UPDATE= 'FACTORS_UPDATE';
export const STOCK_UPDATE= 'STOCK_UPDATE';
export const FIRM_UPDATE='FIRM_UPDATE';
export const RESET_QUERY='RESET_QUERY';
export const FACTOR_SCREENER_RESET='FACTOR_SCREENER_RESET';
export const FACTOR_SCREENER_SAVE = 'FACTOR_SCREENER_SAVE';
export const FACTOR_SCREENER_SAVE_ERROR = 'FACTOR_SCREENER_SAVE_ERROR';
export const BUILD_STRATEGY_QUERY = 'BUILD_STRATEGY_QUERY';
export const UPDATE_STRATEGY_QUERY = 'UPDATE_STRATEGY_QUERY';
export const FACTOR_SCREENER = 'FACTOR_SCREENER';
export const FACTOR_SCREENER_ERROR = 'FACTOR_SCREENER_ERROR';
// Dashboard Queries
export const DASHBOARD_GET = 'DASHBOARD_GET';
export const DASHBOARD_RESET = 'DASHBOARD_RESET';
export const UPDATE_COUNTRY = 'UPDATE_COUNTRY';
// Strategy Monitor
export const STRATEGY_MONITOR_NAME = 'STRATEGY_MONITOR_NAME';
export const STRATEGY_MONITOR_GET = 'STRATEGY_MONITOR_GET';
export const RESET_STRATEGY_MONITOR = 'RESET_STRATEGY_MONITOR';
export const STRATEGY_MONITOR_DELETE = 'STRATEGY_MONITOR_DELETE';
// Watch List
export const WATHLIST_GET = 'WATCHLIST_GET';
