// API
export const API = 'API';
export const API_START = 'API_START';
export const API_END = 'API_END';
export const API_ERROR = 'API_ERROR';
export const API_CLEAR = 'API_CLEAR';

//Application Configuration
export const FETCH_APP_CONFIG = 'FETCH_APP_CONFIG';
export const SET_APP_CONFIG = 'SET_APP_CONFIG';

// old patterns
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

// dashboard
export const FETCH_ALL_DASHBOARD_DATA = 'FETCH_ALL_DASHBOARD_DATA';
export const FETCH_HISTORICAL_PERFORMANCE = 'FETCH_HISTORICAL_PERFORMANCE';
export const SET_HISTORICAL_PERFORMANCE_DATA = 'SET_HISTORICAL_PERFORMANCE_DATA';
export const SET_TICKERS_DATA = 'SET_TICKERS_DATA';
export const FETCH_TICKERS_DATA = 'FETCH_TICKERS_DATA';
export const UPDATE_WATCHLIST = 'UPDATE_WATCHLIST';

// StrategyBuilder
export const FETCH_STRATEGY_RESULTS = 'FETCH_STRATEGY_RESULTS';
export const SET_STRATEGY_RESULTS = 'SET_STRATEGY_RESULTS';
export const SET_STRATEGY_FILTERS = 'SET_STRATEGY_FILTERS';
export const UPDATE_STRATEGY_FILTERS = 'UPDATE_STRATEGY_FILTERS';
export const RESET_STRATEGY_FILTERS = 'RESET_STRATEGY_FILTERS';
export const SET_NEW_WATCHLIST = 'SET_NEW_WATCHLIST';
export const SAVE_STRATEGY = 'SAVE_STRATEGY';

//Watchlist
export const FETCH_WATCHLISTS = 'FETCH_WATCHLISTS';
export const SET_WATCH_LISTS = 'SET_WATCH_LISTS';
export const FETCH_ONE_WATCHLIST_DETAILS = 'FETCH_ONE_WATCHLIST_DETAILS';
export const SET_ONE_WATCHLIST_DETAILS = 'SET_ONE_WATCHLIST_DETAILS';
export const DELETE_WATCHLIST = 'DELETE_WATCHLIST';
export const CLEAR_WATCHLIST = 'CLEAR_WATCHLIST';
export const DELETE_TICKERS = 'DELETE_TICKERS';

//Strategies
export const FETCH_STRATEGIES = 'FETCH_STRATEGIES';
export const SET_STRATEGIES = 'SET_STRATEGIES';
export const FETCH_ONE_STRATEGY_DETAILS = 'FETCH_ONE_STRATEGY_DETAILS';
export const SET_ONE_STRATEGY_DETAILS = 'SET_ONE_STRATEGY_DETAILS';
export const DELETE_STRATEGY = 'DELETE_STRATEGY';
export const CLEAR_STRATEGY = 'CLEAR_STRATEGY';

//resources
export const SET_STRATEGY_NAME = 'SET_STRATEGY_NAME';
export const SET_WATCHLIST_NAME = 'SET_WATCHLIST_NAME';
